# Learning Basic Tensorflow Operations

In [ ]:
# This project aims to demonstrate and understand how a basic deep learning model could be built using Tensorflow

In [1]:
# importing the required libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
%matplotlib inline

ModuleNotFoundError: No module named 'matplotlib'

In [3]:
# set the seed values to generate random values in a predictable fashion.

In [4]:
np.random.seed(101)
tf.set_random_seed(101)

In [5]:
# The following datapoints are fictious and are generated to test the NN's basic working by feeding them in as datapoints.

In [6]:
rand_a = np.random.uniform(0,100,(5,5))
rand_a

array([[ 51.63986277,  57.06675869,   2.84742265,  17.15216562,
         68.52769817],
       [ 83.38968626,  30.69662197,  89.36130797,  72.15438618,
         18.99389542],
       [ 55.42275911,  35.2131954 ,  18.18924027,  78.56017619,
         96.54832224],
       [ 23.23536618,   8.35614337,  60.35484223,  72.89927573,
         27.62388285],
       [ 68.53063288,  51.78674742,   4.84845374,  13.78692376,
         18.69674261]])

In [7]:
rand_b = np.random.uniform(0,100,(5,1))
rand_b

array([[ 99.43179012],
       [ 52.06653967],
       [ 57.87895355],
       [ 73.48190583],
       [ 54.19617722]])

In [ ]:
# The following place holders support for the Logistic Regression operations

In [8]:
a = tf.placeholder(tf.float32)
a

<tf.Tensor 'Placeholder:0' shape=<unknown> dtype=float32>

In [9]:
b = tf.placeholder(tf.float32)
b

<tf.Tensor 'Placeholder_1:0' shape=<unknown> dtype=float32>

In [ ]:
# define operations that needs to be done later

In [10]:
add_op = tf.add(a,b)

In [11]:
mul_op = tf.multiply(a,b)

In [15]:
with tf.Session() as sess:
    print(sess.run(add_op,feed_dict={a:np.random.rand(11,2),b:np.random.rand(1,2)}))

[[ 1.45299339  0.48164111]
 [ 1.36521649  0.96828729]
 [ 1.0382781   1.06047893]
 [ 0.59726322  0.24085706]
 [ 1.20162392  1.02848947]
 [ 0.65967703  0.41358209]
 [ 1.17260826  0.30231267]
 [ 1.20148778  0.6256448 ]
 [ 1.18079448  0.65955776]
 [ 0.54351342  0.36194617]
 [ 1.07532179  0.25844324]]


In [29]:
with tf.Session() as sess:
    print(sess.run(tf.random_normal((1,3))))

[[-0.55499232 -0.40995663  1.52942228]]


In [33]:
with tf.Session() as sess:
    print(sess.run(mul_op,feed_dict={a:rand_a,b:rand_b}))
    
    print("\n")
    
    print(sess.run(add_op ,feed_dict={a:rand_a,b:rand_b}))

[[ 5134.64404297  5674.25         283.12432861  1705.47070312
   6813.83154297]
 [ 4341.8125      1598.26696777  4652.73388672  3756.8293457    988.9463501 ]
 [ 3207.8112793   2038.10290527  1052.77416992  4546.98046875
   5588.11572266]
 [ 1707.37902832   614.02526855  4434.98876953  5356.77734375
   2029.85546875]
 [ 3714.09838867  2806.64379883   262.76763916   747.19854736
   1013.29199219]]


[5 5]


In [60]:
asmple = tf.constant([[1,2,3]])  
print(type(asmple))
type(tf.add(asmple,asmple))

<class 'tensorflow.python.framework.ops.Tensor'>


tensorflow.python.framework.ops.Tensor

# Basic Neural Net with Fictious Data Defined Before

In [ ]:
# Define number of features and dense layers

In [1]:
n_features = 10
n_dense_neurons = 3

In [ ]:
# define the input x for the neural network.
# If there are m training examples, i.e m datapoints(rows) in the dataset
# then the dimension of the placeholder is (m,n_features)
# since we don't know the exact count of datapoints, it's set to (None,n_features)
# placeholder because the data is still unknown and would be fed into it later.
# shape(X) -> (m,n_features)

In [2]:
X = tf.placeholder(tf.float32,(None,n_features))

NameError: name 'tf' is not defined

In [ ]:
# initalize the weights of the neuron to be random with a shape that is (n_features,n_dense_neurons)
# weights are picked randomly by tensorflow
# shape(W) -> (n_features,n_dense_neurons)

In [ ]:
W = tf.Variable(tf.random_normal((n_features,n_dense_neurons)))

In [ ]:
# define a matrix B for biases

In [ ]:
B = tf.Variable(tf.ones(n_dense_neurons))

In [ ]:
# multiply X and W that forms XW
# this is part of the output Equation WX+B

In [ ]:
XW = tf.matmul(X,W)

In [ ]:
# Get (WX + B) 

In [ ]:
Z = tf.add(XW,B)

In [ ]:
# Apply a non linear function like sigmoid that provides a value b/w 0 and 1

In [ ]:
A = tf.sigmoid(Z)

In [ ]:
# make the variables work by initalizing them
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    layer_out = sess.run(A,feed_dict={X:np.random.random([1,n_features])})
    print(layer_out)

In [ ]:
# the previous steps until now were just getting introduced to syntax and ideas

# Simple Regression Example With Weght Adustment

In [ ]:
# Generate X and Y datapoints for regression model

In [ ]:
x_data = np.linspace(0,10,10) + np.random.uniform(-1.5,1.5,10)
x_data

In [ ]:
y_data = np.linspace(0,10,10) + np.random.uniform(-1.5,1.5,10)
y_data

In [ ]:
plt.scatter(x_data,y_data)

In [ ]:
np.random.rand(2)

In [ ]:
# initialize m and b with random values

In [ ]:
w = tf.Variable(0.44)
b = tf.Variable(0.87)

In [ ]:
# initialize error with 0 and proceed
error = 0

# for every datapoint in X and Y
for x,y in zip(x_data,y_data):
    
    # predict the output value from neural network
    
    # i.e weights*inputs+biases 
    y_hat = w*x + b
    
    # calculate the error and minimize it
    error += (y-y_hat)**2 
    

In [ ]:
# use the Gradient Descent Optimizer from tensorflow builtin

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.0001)

In [ ]:
# setup the optimizer to functioning

train = optimizer.minimize(error)

In [ ]:
# define the number of training steps
training_steps = 1000

# initialize the variables
init = tf.global_variables_initializer()


# initialize and run the model
with tf.Session() as sess:
    sess.run(init)
    
    # train the model defined number of times
    # i.e it fixes the weights so many number of times
    for step in range(training_steps):
        sess.run(train)
    
    final_weight, final_bias = sess.run([w,b])
    print("Weight: {}".format(final_weight))
    print("Bias: {}".format(final_bias))

In [ ]:
# generate datapoints from the NN Model's weight and bias prediction
x_test = np.linspace(-1,11,10)

# Get the outputs of NN Model
y_pred_plot = final_weight*x_test+final_bias
y_pred_plot

In [ ]:
# Red line indicates the Neural Network
plt.plot(x_test,y_pred_plot,'r')
plt.scatter(x_data,y_data)