In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
%matplotlib inline 

In [4]:
x_data = np.linspace(0.0,10,1000000)
x_data

array([  0.00000000e+00,   1.00000100e-05,   2.00000200e-05, ...,
         9.99998000e+00,   9.99999000e+00,   1.00000000e+01])

In [5]:
noise = np.random.rand(len(x_data))
noise

array([ 0.08085882,  0.58177859,  0.17501778, ...,  0.75669042,
        0.26553534,  0.71950162])

y = mx + b


b = 5

In [7]:
y_true = (0.5)*x_data + 5 + noise
y_true

array([  5.08085882,   5.58178359,   5.17502778, ...,  10.75668042,
        10.26553034,  10.71950162])

In [8]:
x_df = pd.DataFrame(x_data,columns=['X Data'])
x_df.head()

X Data
0        0.00000
1        0.00001
2        0.00002
3        0.00003
4        0.00004
5        0.00005
6        0.00006
7        0.00007
8        0.00008
9        0.00009
10       0.00010
11       0.00011
12       0.00012
13       0.00013
14       0.00014
15       0.00015
16       0.00016
17       0.00017
18       0.00018
19       0.00019
20       0.00020
21       0.00021
22       0.00022
23       0.00023
24       0.00024
25       0.00025
26       0.00026
27       0.00027
28       0.00028
29       0.00029
...          ...
999970   9.99971
999971   9.99972
999972   9.99973
999973   9.99974
999974   9.99975
999975   9.99976
999976   9.99977
999977   9.99978
999978   9.99979
999979   9.99980
999980   9.99981
999981   9.99982
999982   9.99983
999983   9.99984
999984   9.99985
999985   9.99986
999986   9.99987
999987   9.99988
999988   9.99989
999989   9.99990
999990   9.99991
999991   9.99992
999992   9.99993
999993   9.99994
999994   9.99995
999995   9.99996
999996   9.99997
999997   9.99998
999998   9.99999
999999  10.00000

[1000000 rows x 1 columns]