In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
%matplotlib inline 

In [4]:
x_data = np.linspace(0.0,10,1000000)
x_data

array([  0.00000000e+00,   1.00000100e-05,   2.00000200e-05, ...,
         9.99998000e+00,   9.99999000e+00,   1.00000000e+01])

In [5]:
noise = np.random.rand(len(x_data))
noise

array([ 0.08085882,  0.58177859,  0.17501778, ...,  0.75669042,
        0.26553534,  0.71950162])

y = mx + b


b = 5

In [7]:
y_true = (0.5)*x_data + 5 + noise
y_true

array([  5.08085882,   5.58178359,   5.17502778, ...,  10.75668042,
        10.26553034,  10.71950162])

In [9]:
x_df = pd.DataFrame(x_data,columns=['X Data'])
x_df.head()

X Data
0  0.00000
1  0.00001
2  0.00002
3  0.00003
4  0.00004

In [11]:
y_df = pd.DataFrame(y_true,columns=['Y'])
y_df.head()

Y
0  5.080859
1  5.581784
2  5.175028
3  5.184496
4  5.513528

In [13]:
my_data = pd.concat([x_df,y_df],axis=1)
my_data

X Data          Y
0        0.00000   5.080859
1        0.00001   5.581784
2        0.00002   5.175028
3        0.00003   5.184496
4        0.00004   5.513528
5        0.00005   5.105748
6        0.00006   5.080032
7        0.00007   5.527170
8        0.00008   5.960913
9        0.00009   5.790736
10       0.00010   5.336475
11       0.00011   5.383000
12       0.00012   5.715279
13       0.00013   5.364571
14       0.00014   5.554704
15       0.00015   5.467415
16       0.00016   5.561252
17       0.00017   5.447995
18       0.00018   5.244335
19       0.00019   5.632738
20       0.00020   5.860156
21       0.00021   5.864227
22       0.00022   5.947018
23       0.00023   5.503185
24       0.00024   5.847235
25       0.00025   5.028348
26       0.00026   5.583813
27       0.00027   5.358178
28       0.00028   5.914874
29       0.00029   5.837530
...          ...        ...
999970   9.99971  10.573353
999971   9.99972  10.490463
999972   9.99973  10.627718
999973   9.99974  10.302609
999974   9.99975  10.970698
999975   9.99976  10.170214
999976   9.99977  10.919090
999977   9.99978  10.356946
999978   9.99979  10.680773
999979   9.99980  10.408214
999980   9.99981  10.197768
999981   9.99982  10.487283
999982   9.99983  10.001897
999983   9.99984  10.536963
999984   9.99985  10.050169
999985   9.99986  10.205334
999986   9.99987  10.248007
999987   9.99988  10.918504
999988   9.99989  10.903218
999989   9.99990  10.879012
999990   9.99991  10.880386
999991   9.99992  10.553278
999992   9.99993  10.727678
999993   9.99994  10.199239
999994   9.99995  10.312041
999995   9.99996  10.304894
999996   9.99997  10.183063
999997   9.99998  10.756680
999998   9.99999  10.265530
999999  10.00000  10.719502

[1000000 rows x 2 columns]