In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
%matplotlib inline 

In [4]:
x_data = np.linspace(0.0,10,1000000)
x_data

array([  0.00000000e+00,   1.00000100e-05,   2.00000200e-05, ...,
         9.99998000e+00,   9.99999000e+00,   1.00000000e+01])

In [5]:
noise = np.random.rand(len(x_data))
noise

array([ 0.08085882,  0.58177859,  0.17501778, ...,  0.75669042,
        0.26553534,  0.71950162])

y = mx + b


b = 5

In [7]:
y_true = (0.5)*x_data + 5 + noise
y_true

array([  5.08085882,   5.58178359,   5.17502778, ...,  10.75668042,
        10.26553034,  10.71950162])

In [9]:
x_df = pd.DataFrame(x_data,columns=['X Data'])
x_df.head()

X Data
0  0.00000
1  0.00001
2  0.00002
3  0.00003
4  0.00004

In [10]:
y_df = pd.DataFrame(y_true,columns=['Y'])
y_df.head()

Y
0        5.080859
1        5.581784
2        5.175028
3        5.184496
4        5.513528
5        5.105748
6        5.080032
7        5.527170
8        5.960913
9        5.790736
10       5.336475
11       5.383000
12       5.715279
13       5.364571
14       5.554704
15       5.467415
16       5.561252
17       5.447995
18       5.244335
19       5.632738
20       5.860156
21       5.864227
22       5.947018
23       5.503185
24       5.847235
25       5.028348
26       5.583813
27       5.358178
28       5.914874
29       5.837530
...           ...
999970  10.573353
999971  10.490463
999972  10.627718
999973  10.302609
999974  10.970698
999975  10.170214
999976  10.919090
999977  10.356946
999978  10.680773
999979  10.408214
999980  10.197768
999981  10.487283
999982  10.001897
999983  10.536963
999984  10.050169
999985  10.205334
999986  10.248007
999987  10.918504
999988  10.903218
999989  10.879012
999990  10.880386
999991  10.553278
999992  10.727678
999993  10.199239
999994  10.312041
999995  10.304894
999996  10.183063
999997  10.756680
999998  10.265530
999999  10.719502

[1000000 rows x 1 columns]