In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
%matplotlib inline 

In [4]:
x_data = np.linspace(0.0,10,1000000)
x_data

array([  0.00000000e+00,   1.00000100e-05,   2.00000200e-05, ...,
         9.99998000e+00,   9.99999000e+00,   1.00000000e+01])

In [5]:
noise = np.random.rand(len(x_data))
noise

array([ 0.08085882,  0.58177859,  0.17501778, ...,  0.75669042,
        0.26553534,  0.71950162])

y = mx + b


b = 5

In [7]:
y_true = (0.5)*x_data + 5 + noise
y_true

array([  5.08085882,   5.58178359,   5.17502778, ...,  10.75668042,
        10.26553034,  10.71950162])

In [9]:
x_df = pd.DataFrame(x_data,columns=['X Data'])
x_df.head()

X Data
0  0.00000
1  0.00001
2  0.00002
3  0.00003
4  0.00004

In [11]:
y_df = pd.DataFrame(y_true,columns=['Y'])
y_df.head()

Y
0  5.080859
1  5.581784
2  5.175028
3  5.184496
4  5.513528

In [14]:
my_data = pd.concat([x_df,y_df],axis=1)
my_data.head()

X Data         Y
0  0.00000  5.080859
1  0.00001  5.581784
2  0.00002  5.175028
3  0.00003  5.184496
4  0.00004  5.513528

In [15]:
my_data.sample(25)

X Data          Y
17632   0.176320   5.714206
642365  6.423656   8.891194
331112  3.311123   6.947820
299     0.002990   5.278327
704766  7.047667   8.743392
401299  4.012994   7.247606
293484  2.934843   7.357949
529971  5.299715   8.412789
795695  7.956958   9.689572
280891  2.808913   6.467592
897289  8.972899   9.538064
501323  5.013235   8.181740
27885   0.278850   5.364062
678139  6.781397   8.784956
507129  5.071295   7.559243
540382  5.403825   8.273044
8436    0.084360   5.440798
372111  3.721114   7.336015
494937  4.949375   8.189282
774666  7.746668   9.355419
378633  3.786334   7.446588
904743  9.047439   9.657524
749984  7.499847   9.051927
126168  1.261681   5.975938
944830  9.448309  10.052250
184998  1.849982   6.767242
680515  6.805157   9.204417
676278  6.762787   8.412664
52025   0.520251   6.165953
717974  7.179747   9.030618
...          ...        ...
773320  7.733208   9.523045
204832  2.048322   6.994806
939344  9.393449   9.976600
644435  6.444356   8.539423
372551  3.725514   7.665557
564478  5.644786   8.713812
155375  1.553752   6.473554
908415  9.084159  10.501186
904909  9.049099   9.911994
862529  8.625299   9.650288
398917  3.989174   7.144793
66593   0.665931   5.902527
651591  6.515917   8.383495
732399  7.323997   8.734088
900246  9.002469  10.474526
183727  1.837272   6.771333
890466  8.904669   9.984358
282498  2.824983   7.158070
310904  3.109043   7.180676
928209  9.282099  10.351528
489918  4.899185   7.452848
896436  8.964369   9.735717
160471  1.604712   6.717209
640269  6.402696   8.371108
317459  3.174593   7.076262
63808   0.638081   6.036062
394366  3.943664   7.926681
72153   0.721531   6.219505
125819  1.258191   6.128907
895257  8.952579  10.347988

[250 rows x 2 columns]