In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'1.3.0'

In [3]:
hello = tf.constant("Hello ")
world = tf.constant("World")

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [6]:
with tf.Session() as sess:
    conc = sess.run(hello + world)   

In [7]:
print(conc)

b'Hello World'


In [9]:
a = tf.constant(4)
b = tf.constant(9)

In [10]:
with tf.Session() as sess:
    tot = sess.run(a+b)

In [11]:
print(tot)

13


In [12]:
const_value = tf.constant(10)

In [13]:
fill_mat = tf.fill(dims=(4,4),value=10)

In [14]:
mat_zeros = tf.zeros(shape=(4,4))

In [15]:
mat_ones = tf.ones(shape=(4,4))

In [16]:
rand_norm = tf.random_normal(shape=(4,4))

In [17]:
rand_uniform = tf.random_uniform(shape=(4,4),minval=0,maxval=1)

In [18]:
operations = [const_value,fill_mat,mat_ones,mat_zeros,rand_norm,rand_uniform]

In [19]:
sess = tf.InteractiveSession()

In [20]:
for operation in operations:
    print(sess.run(operation))
    print("\n")

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 0.4025633   0.30864993  1.25761735  2.43999195]
 [ 0.16613193 -0.72783154 -1.54634666 -0.31461823]
 [ 1.14564455  1.25268483 -0.58335096  1.66874456]
 [ 0.1761764   0.08348159 -1.05860209 -1.17255592]]


[[ 0.00860488  0.73761272  0.46449649  0.59919131]
 [ 0.85652387  0.3155092   0.46738279  0.45558405]
 [ 0.36724687  0.28539336  0.73292935  0.50604415]
 [ 0.82063866  0.78087115  0.27363992  0.29582942]]




In [21]:
mat_a = tf.constant(np.arange(1,5,1).reshape(2,2),dtype=tf.int32)

In [22]:
mat_b = tf.constant(np.arange(8,10,1).reshape(2,1),dtype=tf.int32)

In [23]:
mat_a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [24]:
mat_b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [25]:
result = tf.matmul(mat_a,mat_b)

In [26]:
sess.run(result)

array([[26],
       [60]], dtype=int32)

In [27]:
# performs broadcasting 
result = tf.subtract(mat_b,mat_a)

In [73]:
print(sess.run(mat_b))
print("\n")
print(sess.run(mat_a))

[[8]
 [9]]


[[1 2]
 [3 4]]


In [74]:
sess.run(result)

array([[7, 6],
       [6, 5]], dtype=int32)